### PR TITLE
Trailing Cursor: Options to change the rate and image

### PR DESCRIPTION
**Pull request by sylturner**
so i don't forget

### CODE REVIEW

**Comment by tholman** [comment]
Add this variable into the readme as well and I'll happily merge it in

**Comment by sylturner** [comment]
Oh, sorry! I thought I put this PR on my fork 😂 

I still need to test it some more, and I'll update the readme when it's ready. Thanks!

**Comment by sylturner** [comment]
@tholman I tested this more and updated the Readme. I also added an option to override the trailing cursor image. Thanks for this library!

**Comment by tholman** [comment]
Looks good!

Will publish the latest version when I grab a minute 🙏

**Pull request merged**
