### PR TITLE
Following Dot custom color

### PR DESCRIPTION
**Pull request by ZTF666**
I had the pleasure of implementing the trailing effect for one of our internal demos for a product and i got asked the following question so often : 'is it possible to change the color of the dot ?'  , so  i decided to make it happen lol .
I added a couple of lines to make custom colors possible for the following dot . 
Cheers ,ZTF

### CODE REVIEW

**Comment by tholman** [comment]
Nice! Looks like the default color maybe doesn’t have its opacity any more though, fix that up and I’ll merge in!

**Comment by ZTF666** [comment]
Thank you  ! 
Correct me if i'm wrong , the opacity can be set through the hex value of the color if needed !? if i recall, the hex color representation does support the addition of an alpha value i.e : #RRGGBBAA  .
So if for example i chose a black color : #141414 i can add opacity to it by doing something like : #14141450 , thus making the dot have its opacity if needed .

**Comment by tholman** [comment]
Right! The old default was `rgba(50, 50, 50, 0.65)` and in this PR its `#5b5b5b`, would like to keep that opacity on the default either as `rgba(50, 50, 50, 0.65)` or the hex with the alpha

**Comment by ZTF666** [comment]
Alright ! it has been done , thank you for the feedback 🙌.

**Comment by tholman** [comment]
Thanks! Will do the npm deploy when i get a minute, but this is all great.

**Comment by ZTF666** [comment]
Thank you ! cheers 🎊

**Pull request merged**
